name: Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Cache de dependencias de Gradle
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 4. Dar permisos al wrapper de Gradle
      - name: Give Gradle wrapper permission
        run: chmod +x ./braintune-backend/gradlew

      # 5. Construir ShadowJar (solo tu backend)
      - name: Build ShadowJar
        working-directory: ./braintune-backend
        run: ./gradlew clean shadowJar --no-daemon

      # 6. Construir imagen Docker
      - name: Build Docker image
        run: docker build -t braintune-backend:latest ./braintune-backend

      # 7. Probar la imagen Docker
      - name: Run Docker container
        working-directory: ./braintune-backend
        run: docker run -d -p 8080:8080 braintune-backend:latest

      # 8. Subir imagen a Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        working-directory: ./braintune-backend
        run: docker tag braintune-backend:latest your-dockerhub-username/braintune-backend:latest
      - run: docker push your-dockerhub-username/braintune-backend:latest
